# This file was generated by GoReleaser. DO NOT EDIT.
cask "infai" do
  version "0.15.1"

  on_macos do
    on_intel do
      url "https://github.com/dipankardas011/infai/releases/download/v#{version}/infai_#{version}_darwin_amd64.tar.gz"
      sha256 "3adb646db47f27ad19c70608785695195ac6f8efcd757ca7d660dc46aee22b1d"
    end
    on_arm do
      url "https://github.com/dipankardas011/infai/releases/download/v#{version}/infai_#{version}_darwin_arm64.tar.gz"
      sha256 "32c790118217b3f1265cb1343e9058a347d8ca030d4a1d45ceeec610207dd417"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dipankardas011/infai/releases/download/v#{version}/infai_#{version}_linux_amd64.tar.gz"
      sha256 "cc8d0a2e4244218a9b900d2dd9f6c75cedfa7a1f07ce3a33b3a7f6caaea92d9d"
    end
    on_arm do
      url "https://github.com/dipankardas011/infai/releases/download/v#{version}/infai_#{version}_linux_arm64.tar.gz"
      sha256 "517ff5c2926f57e21aa75695b23457a8006ffd64f6c54b28097bd1dcf02a6099"
    end
  end

  name "infai"
  desc "Zero-management launch templates for llama.cpp"
  homepage "https://github.com/dipankardas011/infai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "infai"

  # No zap stanza required

end
