# This file was generated by GoReleaser. DO NOT EDIT.
cask "infai" do
  version "0.11.0"

  on_macos do
    on_intel do
      url "https://github.com/dipankardas011/infai/releases/download/v#{version}/infai_#{version}_darwin_amd64.tar.gz"
      sha256 "170c4d422a82847fc4da44e09719262cb79eec6a6e5a8f112fb885abbcb464a4"
    end
    on_arm do
      url "https://github.com/dipankardas011/infai/releases/download/v#{version}/infai_#{version}_darwin_arm64.tar.gz"
      sha256 "2edb323026a5104d3bf9cd57f11a3530bae68d95a08530c22eef95872de3d018"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dipankardas011/infai/releases/download/v#{version}/infai_#{version}_linux_amd64.tar.gz"
      sha256 "5816b51d736e8f676481ae0e5a672ee6543d845b461e00726398910122f28990"
    end
    on_arm do
      url "https://github.com/dipankardas011/infai/releases/download/v#{version}/infai_#{version}_linux_arm64.tar.gz"
      sha256 "65f0653d0834e13e88e86a1eca9433f2d1e3c66d20566c42f1b90cbe4fffc01c"
    end
  end

  name "infai"
  desc "Zero-management launch templates for llama.cpp"
  homepage "https://github.com/dipankardas011/infai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "infai"

  # No zap stanza required

end
