# This file was generated by GoReleaser. DO NOT EDIT.
cask "infai" do
  version "0.13.0"

  on_macos do
    on_intel do
      url "https://github.com/dipankardas011/infai/releases/download/v#{version}/infai_#{version}_darwin_amd64.tar.gz"
      sha256 "b97661f0ab1b551af98a8d3eb9dd24e659ca577eb7e47fd7060dd641795a490e"
    end
    on_arm do
      url "https://github.com/dipankardas011/infai/releases/download/v#{version}/infai_#{version}_darwin_arm64.tar.gz"
      sha256 "b9eb1ea1429e4d26d8b01cd16d8852ccff8b09697d4b0a2d8ecd8e607f73e332"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dipankardas011/infai/releases/download/v#{version}/infai_#{version}_linux_amd64.tar.gz"
      sha256 "368fc8d3078c13ad64efc55f3207c4d9b83c117dbff20b001ffa1eb7cb900a4a"
    end
    on_arm do
      url "https://github.com/dipankardas011/infai/releases/download/v#{version}/infai_#{version}_linux_arm64.tar.gz"
      sha256 "8730514766e018ce14713cd50324455d5bf2981937ce3dd9647a44067576926b"
    end
  end

  name "infai"
  desc "Zero-management launch templates for llama.cpp"
  homepage "https://github.com/dipankardas011/infai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "infai"

  # No zap stanza required

end
